RSMVC/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace RSMVC.Models
{
    public class Item
    {

       
        public int Id { get; set; }

        [Required]
        [Display(Name = "Items Name")]
        public string? Name { get; set; }

        public decimal? Price { get; set; }

        [Required]
        public string ImagePath { get; set; }

        [Required]
       
        [Display(Name = "Category")]
        public int CategoryId { get; set; }


        public virtual Category Category { get; set; }

        [Required]
        public virtual Availability Availability { get; set; }

        [Required]
        public string Description { get; set; }

        [Display(Name = "Purchased Date:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MMM-yyyy}")]
        public DateTime BoughtDate { get; set; }


        public virtual Condition ItemCondition { get; set; }

        public string Brand { get; set; }

    }

    public enum Availability
    {
        Available,
        Rented,
        Unavailable
    }

    public enum Condition
    {
        New,
        LikeNew,
        Good,
        Fair,
        Poor

    }
}

RSMVC/Controllers/ItemController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RSMVC.Models;

namespace RSMVC.Controllers
{
    public class ItemController : Controller
    {


        readonly static HttpClient client = new ();
        public async Task<IActionResult> Index()
        {
            List<Item> itemsList;
            using (var httpClient = new HttpClient())
            {
                using var response = await httpClient.GetAsync("https://localhost:7121/api/item");
                string apiResponse = await response.Content.ReadAsStringAsync();
                itemsList = JsonConvert.DeserializeObject<List<Item>>(apiResponse);
            }

            return View(itemsList);
        }

       

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            Item item = null;
            HttpResponseMessage response = await client.GetAsync("https://localhost:7121/api/item/" + id);

            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                item = JsonConvert.DeserializeObject<Item>(apiResponse);
                item.Availability.ToString();
            }
           
            
            return View(item);
        }
        
        public ViewResult FindItemsByName() => View();

        [HttpPost]
        public async Task<IActionResult> FindItemsByName(string name)
        {

            List<Item> items = new ();

            HttpResponseMessage response = await client.GetAsync("https://localhost:7121/api/item/search?name=" + name);
                
                if(response.IsSuccessStatusCode)
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    items = JsonConvert.DeserializeObject<List<Item>>(apiResponse);
                }


                return View(items);
        }

        public async Task<IActionResult> GoForRent(int id)
        {
            Item item = null;
            HttpResponseMessage response = await client.GetAsync("https://localhost:7121/api/item/" + id);

            if (response.IsSuccessStatusCode)
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                item = JsonConvert.DeserializeObject<Item>(apiResponse);
            }

           // TempData["selectedItem"] = item;

            return RedirectToAction("RentAnItem", "RentalSystem", item);

        }

        public async Task<IActionResult> UpdateItem(Item item)
        {
            string jsonItem = JsonConvert.SerializeObject(item);
            StringContent content = new StringContent(jsonItem, Encoding.UTF8, "application/json");
            var res = client.PutAsync("https://localhost:7121/api/item/"+ item.Id, content).Result;
            return View(res);
        }

        public ViewResult AddFile() => View();

        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile file)
        {
            string apiResponse = "";
            using (var httpClient = new HttpClient())
            {
                var form = new MultipartFormDataContent();
                await using var fileStream = file.OpenReadStream();
                form.Add(new StreamContent(fileStream), "file", file.FileName);
                using var response = await httpClient.PostAsync("https://localhost:7121/api/item/UploadFile", form);
                response.EnsureSuccessStatusCode();
                apiResponse = await response.Content.ReadAsStringAsync();
            }
            return View((object)apiResponse);




        }
    
    }


}

RSMVC/Controllers/UserController.cs
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RSMVC.Models;


namespace RSMVC.Controllers
{
    public class UserController : Controller
    {


        
        [Authorize]
        public async Task<IActionResult> AllUsers()
        {
            List<ApplicationUser> users = new();

            string URL = "https://localhost:7121/api/users";
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("ContentType", "application/json");

                var plainTextBytes = System.Text.Encoding.UTF8.GetBytes("user:user");
                string val = System.Convert.ToBase64String(plainTextBytes);

                httpClient.DefaultRequestHeaders.Add("Authorization", "basic " + val);

                using (var response = await httpClient.GetAsync(URL))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        users = JsonConvert.DeserializeObject<List<ApplicationUser>>(apiResponse);
                    }
                    else
                        ViewBag.StatusCode = response.StatusCode;
                }
            }
            return View(users);
        }
       
        public ViewResult GetAccount() => View();

        [HttpGet]
        [Route("getuser/{email=unnamed}")]
        public async Task<IActionResult> GetAccount(string email)
        {
            ApplicationUser user = new();
            string URL = "https://localhost:7121/api/getuser/";
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(URL + email))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        user = JsonConvert.DeserializeObject<ApplicationUser>(apiResponse);
                    }
                    else
                        ViewBag.StatusCode = response.StatusCode;

                }

                return View(user);
            }




        }
    }
}

RSMVC/Views/Item/AddFile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model RSMVC.Models.ApplicationUser
@{ Layout = "_Layout"; ViewBag.Title = "Register";}
  
<h2>Regiser</h2>
<a asp-action="Register" class="btn btn-sm btn-primary">Back</a>
<form method="post" enctype="multipart/form-data">
    <input type="file" name="file" />
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Add</button>
    </div>
</form>
  

RSMVC/Views/Item/Details.cshtml
@model RSMVC.Models.Item

        <style >
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
        }

        .title {
            color: grey;
            font-size: 18px;
        }

        button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        a {
            text-decoration: none;
            font-size: 22px;
            color: black;
        }

            button:hover, a:hover {
                opacity: 0.7;
            }
    </style>

@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@{string availability = "Rented";
    StringComparer comparer = StringComparer.OrdinalIgnoreCase;

}



@if (Model != null)
{
<div class="w3-col">
    <div class="w3-col w3-jumbo w3-center w3-margin-top w3-padding-top">
        <h1 class="w3-monospace"><b> @Model.Name</b></h1>
    </div>
    <div class="w3-col w3-margin-top">

        <div class="w3-twothird w3-left">
            <img src="/lib/hpomen.png" width="100%" height="auto" alt="@Model.Brand">


        </div>
        <div class="w3-rest w3-right">
            <p class=" w3-margin-top "> @Model.Price / day  </p>
            <p class="w3-section w3-grey">&emsp;  @Model.Availability</p>

        </div>
    </div>
    <div class="w3-row">
        <div class="w3-col w3-margin-top" style="width:190px">

            <ul class="w3-ul">
                <li><b>Brand:</b></li>
                <li><b>Purchased Date:</b> </li>
                <li><b>Condition:</b></li>
                <li><b>Category:</b> </li>
                <li><b>Description:</b></li>
            </ul>
            <h1 class="w3-hide-large w3-hide-medium" margin="25px"> </h1>

        </div>
        <div class="w3-rest w3-margin-top">

            <ul class="w3-ul">
                <li> @Model.Brand</li>
                <li>@Model.BoughtDate.Year</li>
                <li>@Model.ItemCondition</li>
                <li>@Html.Partial("DisplayTemplates/CategoryModel", Model.Category)</li>
                <li>@Model.Description</li>
            </ul>
            <h1 class="w3-hide-large w3-hide-medium" margin="25px"> </h1>

        </div>
    </div>
    @if (String.Equals(@Model.Availability.ToString(), availability))
    {
        

        <p><a class="w3-button w3-disabled w3-black w3-margin-top w3-right w3-margin-left w3-left w3-large"> RENTED</a></p> }
    else
    {
     
        <p><a asp-controller="Item" asp-action="GoForRent" asp-route-id="@Model.Id" class="w3-button w3-black w3-margin-top w3-margin-left w3-left w3-right w3-large">RENT NOW</a></p>
    }

</div>


    
}

RSMVC/Views/Item/FindItemsByName.cshtml
@model IEnumerable<RSMVC.Models.Item>
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<h2>Get Item <a asp-action="Index" class="btn btn-sm btn-primary">Back</a></h2>
<h3>@ViewBag.StatusCode</h3>
<form method="post">
    <div class="form-group">
        <label for="name">Name:</label>
        <input class="form-control" name="name" />
    </div>
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Get Item</button>
    </div>
</form>
 
@if (Model != null)
{
    <h2>Item</h2>
    <table class="table table-sm table-striped table-bordered m-2">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Image</th>
            <th>Category</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var r in Model)
        {
            <tr>
                <td>@r.Id</td>
                <td>@r.Name</td>
                <td>@r.Price</td>
           
            </tr>
        }
        </tbody>
    </table>
}

RSMVC/Views/Item/Index.cshtml
@model IEnumerable<RSMVC.Models.Item>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "All Items";



}


<div class="w3-display-container w3-container">

    <div class="w3-display-topleft w3-text-black" style="padding:24px 48px">
        <h1 class="w3-jumbo w3-hide-small">Today's Pick</h1>
        <h1 class="w3-hide-large w3-hide-medium" margin="25px"></h1>
    
        <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">RENT NOW</a></p>
    </div>
</div>
<div style="padding: 50px; background-color: #BCC6CC;"></div>
<div style="padding: 50px; background-color: #E5E4E2;"></div>
<!--
<div>
    <img src="/lib/Rent it .png" alt="imagelogo" style="width:95%">
</div> -->

<div class="w3-container w3-text-grey" id="jeans">
    <p>Items</p>
</div>
<div class="w3-container w3-text-grey" >
    <a asp-action="Register" asp-controller="Account" > <b>Register</b></a>
</div>
<div class="w3-container w3-text-grey">
    <a asp-action="AllUsers" asp-controller="User"> <b>Users</b></a>
</div>






<div class="w3-row w3-grayscale">
    @foreach (var r in Model)
        {
        <div class="w3-col l3 s6">
            <div class="w3-container"> 
                <img src="/w3images/jeans1.jpg" style="width:100%">
                <p><a asp-action="Details" asp-controller="Item" asp-route-Id="@r.Id">@r.Name</a><br><b>@r.Price / day</b></p>
            </div>
         </div>
        }
    </div>
        

   @*<table class="table table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>Id</th>
                <th>Namesdfd</th>
                <th>Price</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Image</th>
                <th>Availability</th>
                <th>Bought Date</th>
                <th>Condition</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var r in Model)
            {
                <tr>
                    <td>@r.Id</td>
                    <td><a asp-action="Details" asp-controller="Item" asp-route-Id="@r.Id">@r.Name</a></td>
                    <td>@r.Price</td>
                    <td>@Html.Partial("DisplayTemplates/Category", r.Category)</td>
                    <td>@r.Brand</td>
                    <td>@r.ImagePath</td>
                    <td>@r.Availability</td>
                    <td>@r.BoughtDate</td>
                    <td>@r.ItemCondition</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@r.Id">Details</a>

                    </td>
                    <td>
                        <form asp.action="DeleteItem" method="post">
                            <input type="hidden" value="@r.Id" name="ItemId" />
                            <input type="image" src="/icon/close.png" />
                        </form>
                    </td>
                </tr>

            }

        </tbody>
    </table>*@

RSMVC/Views/Item/RentAnItem.cshtml
@model Item
@{
    Layout = "_Layout";
}


table cellpadding="2" cellspacing="2" border="1">
<tr>
    <th>Name</th>
    <th>Fee Per Day</th>
    <th>Category</th>
    <th>Description</th>
</tr>
<tr>
    <td>@Model.Name</td>
    <td>@Model.Price</td>
    <td>@Model.Category.Name </td>
    <td>@Model.Description</td>
</tr>

<form method="post" enctype="multipart/form-data" asp-controller="RentalSystem" asp-action="RentAnItem">
    <table>
    
        <tr>


            <td> @Model. </td>
            <td><input type="text" id="txtFirstName" name="FirstName"/></td>
        </tr>
        <tr>
            <td>Last Name: </td>
            <td><input type="text" id="txtLastName" name="LastName"/></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"/></td>
        </tr>
        
    </table>
    <hr/>
    @ViewBag.Name
</form>